/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Utils.Constants.numAssemblersJose;
import static Utils.Constants.numProducerClosureJose;
import static Utils.Constants.numProducerCreditsJose;
import static Utils.Constants.numProducerIntroJose;
import static Utils.Constants.numProducerPTJose;
import static Utils.Constants.numProducerStartJose;
import static Utils.ConstantsK.numAssemblerKev;
import static Utils.ConstantsK.numProducerClosureKev;
import static Utils.ConstantsK.numProducerCreditsKev;
import static Utils.ConstantsK.numProducerIntroKev;
import static Utils.ConstantsK.numProducerPTKev;
import static Utils.ConstantsK.numProducerStartKev;
import Utils.GetDatos;

/**
 *
 * @author Jose Rubin
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public static Dashboard InterfazDash= new Dashboard();
	public static GetDatos datum = new GetDatos();
    public Interface() {
        initComponents();
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        PanelPlantaKev = new javax.swing.JPanel();
        AssemblersJ2 = new javax.swing.JTextField();
        ProducersIntro2 = new javax.swing.JTextField();
        ProducersCred2 = new javax.swing.JTextField();
        ProducersInicio2 = new javax.swing.JTextField();
        ProducersClosers2 = new javax.swing.JTextField();
        SumProducersClosers2 = new javax.swing.JButton();
        MinusAssembler2 = new javax.swing.JButton();
        SumAssemblers2 = new javax.swing.JButton();
        SumProducersIntro2 = new javax.swing.JButton();
        MinusProducersIntro2 = new javax.swing.JButton();
        MinusProducersCred2 = new javax.swing.JButton();
        SumProducersCred2 = new javax.swing.JButton();
        MinusProducersStart2 = new javax.swing.JButton();
        SumProducersStart2 = new javax.swing.JButton();
        MinusProducersClosers2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ShowDashboard = new javax.swing.JToggleButton();
        DriveIntro2 = new javax.swing.JTextField();
        DriveCredits2 = new javax.swing.JTextField();
        DriveInicio2 = new javax.swing.JTextField();
        DriveCierre2 = new javax.swing.JTextField();
        DrivePt2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        MinusProducersPT2 = new javax.swing.JButton();
        ProducersPT2 = new javax.swing.JTextField();
        SumProducersPT2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        countdownKevin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RegistroPM2 = new javax.swing.JTextField();
        Director2 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Gastos2 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        Ganancia2 = new javax.swing.JTextField();
        CapsTotal2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        Pm4 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        SalarioPm2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PanelPlantaJose = new javax.swing.JPanel();
        Director1 = new javax.swing.JTextField();
        countdownJose = new javax.swing.JTextField();
        ProducersInicio = new javax.swing.JTextField();
        AssemblersJ1 = new javax.swing.JTextField();
        ProducersIntro = new javax.swing.JTextField();
        ProducersCred = new javax.swing.JTextField();
        ProducersClosers = new javax.swing.JTextField();
        MinusProducersClosers = new javax.swing.JButton();
        SumAssemblers = new javax.swing.JButton();
        MinusAssembler = new javax.swing.JButton();
        MinusProducersIntro = new javax.swing.JButton();
        SumProducersIntro = new javax.swing.JButton();
        SumProducersCred = new javax.swing.JButton();
        MinusProducersCred = new javax.swing.JButton();
        SumProducersStart = new javax.swing.JButton();
        SumProducersClosers = new javax.swing.JButton();
        MinusProducersStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        StartButton = new javax.swing.JToggleButton();
        StopButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        DriveCredits = new javax.swing.JTextField();
        DriveInicio = new javax.swing.JTextField();
        DriveCierre = new javax.swing.JTextField();
        DrivePT = new javax.swing.JTextField();
        DriveIntro = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MinusProducersPT = new javax.swing.JButton();
        ProducersPT = new javax.swing.JTextField();
        SumProducersPT = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Ganancia1 = new javax.swing.JTextField();
        RegistroPM1 = new javax.swing.JTextField();
        Gastos1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        countdownKevin1 = new javax.swing.JTextField();
        CapsTotal = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        Pm3 = new javax.swing.JTextField();
        SalarioPm1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPlantaKev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AssemblersJ2.setEditable(false);
        AssemblersJ2.setText(Integer.toString(numAssemblerKev));
        AssemblersJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblersJ2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(AssemblersJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 50, 40));

        ProducersIntro2.setEditable(false);
        ProducersIntro2.setText(Integer.toString(numProducerIntroKev));
        ProducersIntro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersIntro2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(ProducersIntro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 50, 40));

        ProducersCred2.setEditable(false);
        ProducersCred2.setText(Integer.toString(numProducerCreditsKev));
        ProducersCred2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersCred2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(ProducersCred2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 50, 40));

        ProducersInicio2.setEditable(false);
        ProducersInicio2.setText(Integer.toString(numProducerStartKev));
        ProducersInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersInicio2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(ProducersInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 50, 40));

        ProducersClosers2.setEditable(false);
        ProducersClosers2.setText(Integer.toString(numProducerClosureKev));
        ProducersClosers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersClosers2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(ProducersClosers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, 40));

        SumProducersClosers2.setText("+");
        SumProducersClosers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersClosers2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SumProducersClosers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 50, 40));

        MinusAssembler2.setText("-");
        MinusAssembler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusAssembler2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(MinusAssembler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 50, 40));

        SumAssemblers2.setText("+");
        SumAssemblers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumAssemblers2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SumAssemblers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 50, 40));

        SumProducersIntro2.setText("+");
        SumProducersIntro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersIntro2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SumProducersIntro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 50, 40));

        MinusProducersIntro2.setText("-");
        MinusProducersIntro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersIntro2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(MinusProducersIntro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 50, 40));

        MinusProducersCred2.setText("-");
        MinusProducersCred2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersCred2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(MinusProducersCred2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 50, 40));

        SumProducersCred2.setText("+");
        SumProducersCred2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersCred2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SumProducersCred2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 50, 40));

        MinusProducersStart2.setText("-");
        MinusProducersStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersStart2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(MinusProducersStart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 50, 40));

        SumProducersStart2.setText("+");
        SumProducersStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersStart2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SumProducersStart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 50, 40));

        MinusProducersClosers2.setText("-");
        MinusProducersClosers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersClosers2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(MinusProducersClosers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, 40));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Planta de Productor de Contenido Kevin");
        PanelPlantaKev.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ensambladores");
        PanelPlantaKev.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Productores de Intro");
        PanelPlantaKev.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Productores de Creditos");
        PanelPlantaKev.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Productores de Cierre");
        PanelPlantaKev.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Productores de PT");
        PanelPlantaKev.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        ShowDashboard.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ShowDashboard.setText("Dashboard");
        ShowDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDashboardActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(ShowDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 110, 40));

        DriveIntro2.setEditable(false);
        DriveIntro2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveIntro2.setText("0");
        DriveIntro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveIntro2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(DriveIntro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 20, 20));

        DriveCredits2.setEditable(false);
        DriveCredits2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveCredits2.setText("0");
        DriveCredits2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveCredits2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(DriveCredits2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 20, 20));

        DriveInicio2.setEditable(false);
        DriveInicio2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveInicio2.setText("0");
        DriveInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveInicio2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(DriveInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 20, 20));

        DriveCierre2.setEditable(false);
        DriveCierre2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveCierre2.setText("0");
        DriveCierre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveCierre2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(DriveCierre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 20, 20));

        DrivePt2.setEditable(false);
        DrivePt2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DrivePt2.setText("0");
        DrivePt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivePt2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(DrivePt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 20, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Drives:");
        PanelPlantaKev.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 80, -1));

        jLabel32.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Intro");
        PanelPlantaKev.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 40, -1));

        jLabel33.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Credits");
        PanelPlantaKev.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 50, -1));

        jLabel34.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Inicio");
        PanelPlantaKev.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 40, -1));

        jLabel35.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Cierre");
        PanelPlantaKev.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 50, -1));

        jLabel36.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("PT");
        PanelPlantaKev.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 70, -1));

        MinusProducersPT2.setText("-");
        MinusProducersPT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersPT2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(MinusProducersPT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 50, 40));

        ProducersPT2.setEditable(false);
        ProducersPT2.setText(Integer.toString(numProducerPTKev));
        ProducersPT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersPT2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(ProducersPT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 50, 40));

        SumProducersPT2.setText("+");
        SumProducersPT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersPT2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SumProducersPT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 50, 40));

        jLabel30.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Productores de Inicio");
        PanelPlantaKev.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        countdownKevin.setEditable(false);
        countdownKevin.setText("1");
        countdownKevin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countdownKevinActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(countdownKevin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 30, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Countdown:");
        PanelPlantaKev.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 120, 20));

        RegistroPM2.setEditable(false);
        RegistroPM2.setText("0");
        RegistroPM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroPM2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(RegistroPM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 120, 20));

        Director2.setEditable(false);
        Director2.setText("Durmiendo...");
        Director2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Director2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(Director2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 120, 20));

        jLabel42.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Director:");
        PanelPlantaKev.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 60, -1));

        jLabel43.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Faltas PM: ");
        PanelPlantaKev.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 90, -1));

        jLabel44.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Gastos:");
        PanelPlantaKev.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 60, -1));

        Gastos2.setEditable(false);
        Gastos2.setText("1");
        Gastos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gastos2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(Gastos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 30, 20));

        jLabel45.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Ganancia:");
        PanelPlantaKev.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 70, -1));

        Ganancia2.setEditable(false);
        Ganancia2.setText("1");
        Ganancia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ganancia2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(Ganancia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 30, 20));

        CapsTotal2.setEditable(false);
        CapsTotal2.setText("0");
        CapsTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapsTotal2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(CapsTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 30, 30));

        jLabel47.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Capítulos");
        jLabel47.setToolTipText("");
        PanelPlantaKev.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 60, 30));

        jLabel50.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("PM:");
        PanelPlantaKev.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 40, -1));

        Pm4.setEditable(false);
        Pm4.setText("Durmiendo...");
        Pm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pm4ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(Pm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 120, 20));

        jLabel51.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Salario PM: ");
        PanelPlantaKev.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 90, -1));

        SalarioPm2.setEditable(false);
        SalarioPm2.setText("0");
        SalarioPm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioPm2ActionPerformed(evt);
            }
        });
        PanelPlantaKev.add(SalarioPm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/got.png"))); // NOI18N
        PanelPlantaKev.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-960, -10, 1390, 960));

        getContentPane().add(PanelPlantaKev, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 430, 570));

        PanelPlantaJose.setBackground(new java.awt.Color(2, 51, 54));
        PanelPlantaJose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Director1.setEditable(false);
        Director1.setText("Durmiendo...");
        Director1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Director1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(Director1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 120, 20));

        countdownJose.setEditable(false);
        countdownJose.setText("1");
        countdownJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countdownJoseActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(countdownJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 30, 40));

        ProducersInicio.setEditable(false);
        ProducersInicio.setText(Integer.toString(numProducerStartJose));
        ProducersInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersInicioActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(ProducersInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 50, 40));

        AssemblersJ1.setEditable(false);
        AssemblersJ1.setText(Integer.toString(numAssemblersJose));
        AssemblersJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssemblersJ1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(AssemblersJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 50, 40));

        ProducersIntro.setEditable(false);
        ProducersIntro.setText(Integer.toString(numProducerIntroJose));
        ProducersIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersIntroActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(ProducersIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, 40));

        ProducersCred.setEditable(false);
        ProducersCred.setText(Integer.toString(numProducerCreditsJose));
        ProducersCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersCredActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(ProducersCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 50, 40));

        ProducersClosers.setEditable(false);
        ProducersClosers.setText(Integer.toString(numProducerClosureJose));
        ProducersClosers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersClosersActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(ProducersClosers, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 50, 40));

        MinusProducersClosers.setText("-");
        MinusProducersClosers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersClosersActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(MinusProducersClosers, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 50, 40));

        SumAssemblers.setText("+");
        SumAssemblers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumAssemblersActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SumAssemblers, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 50, 40));

        MinusAssembler.setText("-");
        MinusAssembler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusAssemblerActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(MinusAssembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 50, 40));

        MinusProducersIntro.setText("-");
        MinusProducersIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersIntroActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(MinusProducersIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 50, 40));

        SumProducersIntro.setText("+");
        SumProducersIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersIntroActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SumProducersIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, 40));

        SumProducersCred.setText("+");
        SumProducersCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersCredActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SumProducersCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 50, 40));

        MinusProducersCred.setText("-");
        MinusProducersCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersCredActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(MinusProducersCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 50, 40));

        SumProducersStart.setText("+");
        SumProducersStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersStartActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SumProducersStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, 40));

        SumProducersClosers.setText("+");
        SumProducersClosers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersClosersActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SumProducersClosers, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 50, 40));

        MinusProducersStart.setText("-");
        MinusProducersStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersStartActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(MinusProducersStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 50, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Planta de Productor de Contenido Jose");
        PanelPlantaJose.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Productores de Inicio");
        PanelPlantaJose.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Ensambladores");
        PanelPlantaJose.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Productores de Intro");
        PanelPlantaJose.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Productores de Creditos");
        PanelPlantaJose.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Productores de Cierre");
        PanelPlantaJose.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        StartButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 70, 40));

        StopButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(StopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 70, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Countdown:");
        PanelPlantaJose.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 120, 20));

        DriveCredits.setEditable(false);
        DriveCredits.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveCredits.setText("0");
        DriveCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveCreditsActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(DriveCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 20, 20));

        DriveInicio.setEditable(false);
        DriveInicio.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveInicio.setText("0");
        DriveInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveInicioActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(DriveInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 20, 20));

        DriveCierre.setEditable(false);
        DriveCierre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveCierre.setText("0");
        DriveCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveCierreActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(DriveCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 20, 20));

        DrivePT.setEditable(false);
        DrivePT.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DrivePT.setText("0");
        DrivePT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivePTActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(DrivePT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 20, 20));

        DriveIntro.setEditable(false);
        DriveIntro.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        DriveIntro.setText("0");
        DriveIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveIntroActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(DriveIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 20, 20));

        jLabel27.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Credits");
        PanelPlantaJose.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 50, -1));

        jLabel28.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Inicio");
        PanelPlantaJose.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 40, -1));

        jLabel29.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Cierre");
        PanelPlantaJose.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 50, -1));

        jLabel31.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Gastos:");
        PanelPlantaJose.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 60, -1));

        jLabel37.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Capítulos");
        jLabel37.setToolTipText("");
        PanelPlantaJose.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 70, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Drives:");
        PanelPlantaJose.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 80, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Productores de PT");
        PanelPlantaJose.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        MinusProducersPT.setText("-");
        MinusProducersPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusProducersPTActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(MinusProducersPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 50, 40));

        ProducersPT.setEditable(false);
        ProducersPT.setText(Integer.toString(numProducerPTJose));
        ProducersPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducersPTActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(ProducersPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 50, 40));

        SumProducersPT.setText("+");
        SumProducersPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumProducersPTActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SumProducersPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 50, 40));

        jLabel39.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Faltas PM: ");
        PanelPlantaJose.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 80, -1));

        jLabel38.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Ganancia:");
        PanelPlantaJose.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 70, -1));

        jLabel40.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Director:");
        PanelPlantaJose.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 60, -1));

        jLabel41.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Intro");
        PanelPlantaJose.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 40, -1));

        Ganancia1.setEditable(false);
        Ganancia1.setText("1");
        Ganancia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ganancia1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(Ganancia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 30, 20));

        RegistroPM1.setEditable(false);
        RegistroPM1.setText("0");
        RegistroPM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroPM1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(RegistroPM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 120, 20));

        Gastos1.setEditable(false);
        Gastos1.setText("1");
        Gastos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gastos1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(Gastos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 30, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tiempo:");
        PanelPlantaJose.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 80, 20));

        countdownKevin1.setEditable(false);
        countdownKevin1.setText("1");
        countdownKevin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countdownKevin1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(countdownKevin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 30, 40));

        CapsTotal.setEditable(false);
        CapsTotal.setText("0");
        CapsTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapsTotalActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(CapsTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 30, 30));

        jLabel46.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("PT");
        PanelPlantaJose.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 70, -1));

        jLabel48.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("PM:");
        PanelPlantaJose.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 40, -1));

        jLabel49.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Salario PM:");
        PanelPlantaJose.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 80, -1));

        Pm3.setEditable(false);
        Pm3.setText("Durmiendo...");
        Pm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pm3ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(Pm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 120, 20));

        SalarioPm1.setEditable(false);
        SalarioPm1.setText("0");
        SalarioPm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioPm1ActionPerformed(evt);
            }
        });
        PanelPlantaJose.add(SalarioPm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 120, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/r&morty.jpg"))); // NOI18N
        PanelPlantaJose.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-930, -50, 1600, 780));

        getContentPane().add(PanelPlantaJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProducersInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersInicioActionPerformed

    private void AssemblersJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblersJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblersJ1ActionPerformed

    private void ProducersIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersIntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersIntroActionPerformed

    private void ProducersCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersCredActionPerformed

    private void ProducersClosersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersClosersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersClosersActionPerformed

    private void MinusProducersClosersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersClosersActionPerformed
		Utils.InterfaceFunctions.minusProducersClosers();
    }//GEN-LAST:event_MinusProducersClosersActionPerformed

    private void AssemblersJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssemblersJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssemblersJ2ActionPerformed

    private void ProducersIntro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersIntro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersIntro2ActionPerformed

    private void ProducersCred2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersCred2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersCred2ActionPerformed

    private void ProducersInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersInicio2ActionPerformed

    private void ProducersClosers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersClosers2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersClosers2ActionPerformed

    private void SumAssemblersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumAssemblersActionPerformed
        // TODO add your handling code here:
		Utils.InterfaceFunctions.sumAssemblers();
    }//GEN-LAST:event_SumAssemblersActionPerformed

    private void MinusAssemblerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusAssemblerActionPerformed
		Utils.InterfaceFunctions.minusAssemblers();
    }//GEN-LAST:event_MinusAssemblerActionPerformed

    private void MinusProducersIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersIntroActionPerformed
        Utils.InterfaceFunctions.minusProducersIntro();
    }//GEN-LAST:event_MinusProducersIntroActionPerformed

    private void SumProducersIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersIntroActionPerformed
        // TODO add your handling code here:
		Utils.InterfaceFunctions.sumProducersIntro();
    }//GEN-LAST:event_SumProducersIntroActionPerformed

    private void SumProducersCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersCredActionPerformed
        // TODO add your handling code here:
		Utils.InterfaceFunctions.sumProducersCred();
    }//GEN-LAST:event_SumProducersCredActionPerformed

    private void MinusProducersCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersCredActionPerformed
		Utils.InterfaceFunctions.minusProducersCred();
    }//GEN-LAST:event_MinusProducersCredActionPerformed

    private void SumProducersStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersStartActionPerformed
        // TODO add your handling code here:
		Utils.InterfaceFunctions.sumProducersStart();
    }//GEN-LAST:event_SumProducersStartActionPerformed

    private void SumProducersClosersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersClosersActionPerformed
        // TODO add your handling code here:
		Utils.InterfaceFunctions.sumProducersClosers();
    }//GEN-LAST:event_SumProducersClosersActionPerformed

    private void MinusProducersStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersStartActionPerformed
		Utils.InterfaceFunctions.minusProducersStart();
    }//GEN-LAST:event_MinusProducersStartActionPerformed

    private void SumProducersClosers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersClosers2ActionPerformed
        Utils.InterfaceFunctionsK.sumProducersClosers();
    }//GEN-LAST:event_SumProducersClosers2ActionPerformed

    private void MinusAssembler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusAssembler2ActionPerformed
        Utils.InterfaceFunctionsK.minusAssemblers();
        // TODO add your handling code here:
    }//GEN-LAST:event_MinusAssembler2ActionPerformed

    private void SumAssemblers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumAssemblers2ActionPerformed
        Utils.InterfaceFunctionsK.sumAssemblers();
    }//GEN-LAST:event_SumAssemblers2ActionPerformed

    private void SumProducersIntro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersIntro2ActionPerformed
        Utils.InterfaceFunctionsK.sumProducersIntro();
    }//GEN-LAST:event_SumProducersIntro2ActionPerformed

    private void MinusProducersIntro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersIntro2ActionPerformed
        Utils.InterfaceFunctionsK.minusProducersIntro();

    }//GEN-LAST:event_MinusProducersIntro2ActionPerformed

    private void MinusProducersCred2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersCred2ActionPerformed
        Utils.InterfaceFunctionsK.minusProducersCred();
    }//GEN-LAST:event_MinusProducersCred2ActionPerformed

    private void SumProducersCred2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersCred2ActionPerformed
        Utils.InterfaceFunctionsK.sumProducersCred();
    }//GEN-LAST:event_SumProducersCred2ActionPerformed

    private void MinusProducersStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersStart2ActionPerformed
        Utils.InterfaceFunctionsK.minusProducersStart();
    }//GEN-LAST:event_MinusProducersStart2ActionPerformed

    private void SumProducersStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersStart2ActionPerformed
        Utils.InterfaceFunctionsK.sumProducersStart();
    }//GEN-LAST:event_SumProducersStart2ActionPerformed

    private void MinusProducersClosers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersClosers2ActionPerformed
        Utils.InterfaceFunctionsK.minusProducersClosers();
    }//GEN-LAST:event_MinusProducersClosers2ActionPerformed

    private void ShowDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDashboardActionPerformed
        // TODO add your handling code here:

		datum.getDataforDashboard();
        InterfazDash.setVisible(true);
    }//GEN-LAST:event_ShowDashboardActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        Utils.InterfaceFunctionsK.startRun();
        Utils.InterfaceFunctions.startRun();
    }//GEN-LAST:event_StartButtonActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        Utils.InterfaceFunctionsK.stopRun();
        Utils.InterfaceFunctions.stopRun();
    }//GEN-LAST:event_StopButtonActionPerformed

    private void DriveCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveCreditsActionPerformed

    private void DriveInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveInicioActionPerformed

    private void DriveCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveCierreActionPerformed

    private void DrivePTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivePTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrivePTActionPerformed

    private void DriveIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveIntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveIntroActionPerformed

    private void DriveIntro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveIntro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveIntro2ActionPerformed

    private void DriveCredits2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveCredits2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveCredits2ActionPerformed

    private void DriveInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveInicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveInicio2ActionPerformed

    private void DriveCierre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveCierre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveCierre2ActionPerformed

    private void DrivePt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivePt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrivePt2ActionPerformed

    private void countdownJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countdownJoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countdownJoseActionPerformed

    private void MinusProducersPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersPTActionPerformed
        // TODO add your handling code here:		
		Utils.InterfaceFunctions.minusProducersPT();
    }//GEN-LAST:event_MinusProducersPTActionPerformed

    private void ProducersPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersPTActionPerformed

    private void SumProducersPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersPTActionPerformed
        // TODO add your handling code here:
		Utils.InterfaceFunctions.sumProducersPT();
    }//GEN-LAST:event_SumProducersPTActionPerformed

    private void MinusProducersPT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusProducersPT2ActionPerformed
        Utils.InterfaceFunctionsK.minusProducersPT();
    }//GEN-LAST:event_MinusProducersPT2ActionPerformed

    private void ProducersPT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducersPT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducersPT2ActionPerformed

    private void SumProducersPT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumProducersPT2ActionPerformed
        Utils.InterfaceFunctionsK.sumProducersPT();
    }//GEN-LAST:event_SumProducersPT2ActionPerformed

    private void countdownKevinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countdownKevinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countdownKevinActionPerformed

    private void Director1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Director1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Director1ActionPerformed

    private void Ganancia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ganancia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ganancia1ActionPerformed

    private void Gastos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gastos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gastos1ActionPerformed

    private void RegistroPM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroPM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroPM1ActionPerformed

    private void RegistroPM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroPM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroPM2ActionPerformed

    private void Director2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Director2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Director2ActionPerformed

    private void Gastos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gastos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gastos2ActionPerformed

    private void Ganancia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ganancia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ganancia2ActionPerformed

    private void countdownKevin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countdownKevin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countdownKevin1ActionPerformed

    private void CapsTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapsTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapsTotalActionPerformed

    private void CapsTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapsTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapsTotal2ActionPerformed

    private void Pm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pm3ActionPerformed

    private void SalarioPm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioPm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioPm1ActionPerformed

    private void Pm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pm4ActionPerformed

    private void SalarioPm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioPm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioPm2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField AssemblersJ1;
    public static javax.swing.JTextField AssemblersJ2;
    public static javax.swing.JTextField CapsTotal;
    public static javax.swing.JTextField CapsTotal2;
    public static javax.swing.JTextField Director1;
    public static javax.swing.JTextField Director2;
    public static javax.swing.JTextField DriveCierre;
    public static javax.swing.JTextField DriveCierre2;
    public static javax.swing.JTextField DriveCredits;
    public static javax.swing.JTextField DriveCredits2;
    public static javax.swing.JTextField DriveInicio;
    public static javax.swing.JTextField DriveInicio2;
    public static javax.swing.JTextField DriveIntro;
    public static javax.swing.JTextField DriveIntro2;
    public static javax.swing.JTextField DrivePT;
    public static javax.swing.JTextField DrivePt2;
    public static javax.swing.JTextField Ganancia1;
    public static javax.swing.JTextField Ganancia2;
    public static javax.swing.JTextField Gastos1;
    public static javax.swing.JTextField Gastos2;
    private javax.swing.JButton MinusAssembler;
    private javax.swing.JButton MinusAssembler2;
    private javax.swing.JButton MinusProducersClosers;
    private javax.swing.JButton MinusProducersClosers2;
    private javax.swing.JButton MinusProducersCred;
    private javax.swing.JButton MinusProducersCred2;
    private javax.swing.JButton MinusProducersIntro;
    private javax.swing.JButton MinusProducersIntro2;
    private javax.swing.JButton MinusProducersPT;
    private javax.swing.JButton MinusProducersPT2;
    private javax.swing.JButton MinusProducersStart;
    private javax.swing.JButton MinusProducersStart2;
    private javax.swing.JPanel PanelPlantaJose;
    private javax.swing.JPanel PanelPlantaKev;
    public static javax.swing.JTextField Pm3;
    public static javax.swing.JTextField Pm4;
    public static javax.swing.JTextField ProducersClosers;
    public static javax.swing.JTextField ProducersClosers2;
    public static javax.swing.JTextField ProducersCred;
    public static javax.swing.JTextField ProducersCred2;
    public static javax.swing.JTextField ProducersInicio;
    public static javax.swing.JTextField ProducersInicio2;
    public static javax.swing.JTextField ProducersIntro;
    public static javax.swing.JTextField ProducersIntro2;
    public static javax.swing.JTextField ProducersPT;
    public static javax.swing.JTextField ProducersPT2;
    public static javax.swing.JTextField RegistroPM1;
    public static javax.swing.JTextField RegistroPM2;
    public static javax.swing.JTextField SalarioPm1;
    public static javax.swing.JTextField SalarioPm2;
    private javax.swing.JToggleButton ShowDashboard;
    private javax.swing.JToggleButton StartButton;
    private javax.swing.JToggleButton StopButton;
    private javax.swing.JButton SumAssemblers;
    private javax.swing.JButton SumAssemblers2;
    private javax.swing.JButton SumProducersClosers;
    private javax.swing.JButton SumProducersClosers2;
    private javax.swing.JButton SumProducersCred;
    private javax.swing.JButton SumProducersCred2;
    private javax.swing.JButton SumProducersIntro;
    private javax.swing.JButton SumProducersIntro2;
    private javax.swing.JButton SumProducersPT;
    private javax.swing.JButton SumProducersPT2;
    private javax.swing.JButton SumProducersStart;
    private javax.swing.JButton SumProducersStart2;
    public static javax.swing.JTextField countdownJose;
    public static javax.swing.JTextField countdownKevin;
    public static javax.swing.JTextField countdownKevin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
